"""Proper models initialized

Revision ID: 91f8cedadbed
Revises: 650f15090d43
Create Date: 2024-10-05 16:23:34.688751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f8cedadbed'
down_revision = '650f15090d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_training_details_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_created_at'))
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('training_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_details_created_at'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
