"""Añadir campos name, surname y alias al modelo User

Revision ID: bdf9f828a207
Revises: 91f8cedadbed
Create Date: 2024-10-07 16:28:46.426751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf9f828a207'
down_revision = '91f8cedadbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_training_details_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_details_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_training_sessions_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('alias', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_column('alias')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_updated_at'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('training_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_details_updated_at'))
        batch_op.drop_index(batch_op.f('ix_training_details_timestamp'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('hash_id')

    # ### end Alembic commands ###
